### ISSUE TITLE
Getting plain text if I convert html table to JIRA markup rich text

### ISSUE THREAD

**Issue by dchouksey89** [paul-nelson-baker/html-to-jira-markup#2] opened 2018-01-11 16:51 UTC
I am trying to convert HTML string but it is giving me plain text. I need to convert to Jira markup which i can push to the description field of JIRA issue. 

**HTML String**
`
	String htmlString="<html><body><table style=\"width:100%\">\r\n" + 
				"  <tr><th>Firstname</th><th>Lastname</th><th>Age</th></tr>\r\n" + 
				"  <tr><td>Jill</td><td>Smith</td><td>50</td></tr>\r\n" + 
				"  <tr><td>Eve</td><td>Jackson</td><td>94</td></tr>\r\n" + 
				"  <tr><td>John</td><td>Doe</td><td>80</td></tr>\r\n" + 
				"</table></body></html>";	

`

**Output:**
`FirstnameLastnameth>AgeJillSmith50EveJackson94JohnDoe80`

**Expeted outout: somthing like that for table format**
`
 ||Heading 1||Heading 2||
 |Col A1|Col A1|
 |Col A1| Col A1|
 |Col A1|  Col A1|
 |Col A1|Col A2|
`

**Comment by nikole-dunixi** [comment] 2018-01-12 01:37
Hi @dchouksey89 :)

The problem is with the HTML you have. Currently I see all the data mushed into a single table element, delimited by `\r\n`. HTML delimits by element. Here's the input you're looking for:

``` html
<table>
<tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Age</th>
</tr>
<tr>
  <td>Jill</td>
  <td>Smith</td>
  <td>50</td>
</tr>
<tr>
  <td>Eve</td>
  <td>Jackson</td>
  <td>94</td>
</tr>
<tr>
  <td>John</td>
  <td>Doe</td>
  <td>80</td>
</tr>
</table>
```
Each row represents an one of your items, and the first row specifically displays the headers. With this as your input you get the following output:
``` markdown
|| First Name || Last Name || Age ||
| Jill | Smith | 50 |
| Eve | Jackson | 94 |
| John | Doe | 80 |
```

You can't preview it here, unfortunately. However when I enter this into JIRA I can see this:
![image](https://user-images.githubusercontent.com/1402178/34855542-7f42b06e-f6fd-11e7-8d26-d871bbd14e4a.png)

I've committed an example for you to reference, however, I recommend that you read some [w3schools reference material](https://www.w3schools.com/tags/tag_th.asp) to help you along in the future.

**Closed as completed by nikole-dunixi** 2018-01-12 01:37 UTC

**Comment by dchouksey89** [comment] 2018-01-12 07:16
Thanks !! Working like charm :-)
